import { DEFAULT_WORKER_TTL_SECONDS } from "@decomp-orchestrator/core/state";
import { DEFAULT_PI_MODEL, DEFAULT_PI_PROVIDER, DEFAULT_PI_THINKING_LEVEL, DEFAULT_STATE_DIR_NAME } from "./defaults.js";

export function usage(): string {
  return [
    "Usage:",
    "  decomp-orchestrator [global flags] init-run [--goal-kind kind] [--goal-value n] [--desired-workers n] [--candidate-limit n] [--graph-db path]",
    "  decomp-orchestrator [global flags] tick [--run-id id] [--epoch-size n|full] [--epoch-ready-queue-size n] [--candidate-limit n] [--candidate-window n] [--queue-target-size n] [--graph-db path]",
    "  decomp-orchestrator [global flags] worker [--run-id id] [--worker-id id] [--report-type type] [--base-rev rev] [--ttl-seconds n] [--repair-attempts n] [--post-return-check-command cmd] [--graph-db path]",
    "  decomp-orchestrator [global flags] run-loop [--run-id id] [--max-workers n] [--worker-thinking-level level] [--idle-sleep-ms n] [--max-iterations n] [--max-idle-iterations n] [epoch/refill flags] [replan flags] [--graph-db path]",
    "  decomp-orchestrator [global flags] trigger-agent [same flags as run-loop; compatibility alias]",
    "  decomp-orchestrator [global flags] bootstrap [same flags as run-loop; compatibility alias]",
    "  decomp-orchestrator [global flags] babysit [--run-id id] [trigger flags] [--max-restarts n] [--restart-delay-ms n]",
    "  decomp-orchestrator [global flags] checkpoint-run [--run-id id] [--artifact-dir path] [--allow-active-leases] [--title text]",
    "  decomp-orchestrator [global flags] recover-leases [--run-id id] [--force] [--lease-id id] [--worker-id id] [--reason text]",
    "  decomp-orchestrator [global flags] epoch-run [--run-id id] [--worktree path] [--configure-command cmd] [--regression-pause-threshold n] [--regression-requeue-limit n] [--no-requeue] [--label text]",
    "  decomp-orchestrator [global flags] report-run [--reset-baseline]",
    "  decomp-orchestrator [global flags] regression-check [--run-id id] [--target changes_all] [--report-title title] [--report-max-rows n] [--require-pr-promotion]",
    "  decomp-orchestrator [global flags] qa-repair [--run-id id] [--base-ref ref] [--checkpoint path|none] [--scan-json path] [--candidate-files a,b] [--candidate-list path] [--all-scan-files] [--repair-warnings] [--run-agents] [--max-items n] [--item-id id] [--score-check-command cmd] [--build-check-command cmd] [--regression-check-command cmd] [--output-dir path]",
    "  decomp-orchestrator [global flags] pr-split-plan [--base-ref ref] [--strategy deterministic|agent] [--group-mode melee-subsystem|top-dir] [--max-files-per-pr n] [--checkpoint path] [--slice-check-command cmd] [--json] [--output path]",
    "  decomp-orchestrator [global flags] pr-draft-qa (--pr n | --pr-url url | --create-draft --title title) [--repo owner/name] [--run-agents] [--max-repair-rounds n] [--comment-unresolved] [--advisory-warnings] [--allow-lower-score-repairs] [--wait-ci] [--local-check-command cmd]",
    "  decomp-orchestrator [global flags] pr-preship-review --plan path (--all | --slice id) [--base ref] [--head ref] [--thinking level] [--run-id id] [--dry-run]",
    "  decomp-orchestrator [global flags] reconcile [--mode ship-validate|sync-merge] [--run-id id] [--base-ref ref] [--attempt-budget n] [--context-file path] [--allow-missing-regression-check]",
    "  decomp-orchestrator [global flags] save-point [--trigger manual|init|pause|checkpoint|qa|ship|sync|fresh] [--label text] [--base-ref ref] [--no-commit] [--list] [--limit n]",
    "  decomp-orchestrator [global flags] kg-sources",
    "  decomp-orchestrator [global flags] kg-status [--graph-db path]",
    "  decomp-orchestrator [global flags] kg-import-agent-state [--input db] [--output jsonl]",
    "  decomp-orchestrator [global flags] kg-curate [--run-id id] [--output jsonl] [--worker-limit n] [--pr-limit n] [--progress-only]",
    "  decomp-orchestrator [global flags] kg-maintain [--run-id id] [--run-pr-agent] [--run-curator-agent] [--curator-agent-record-limit n] [--curator-agent-batch-size n] [--curator-agent-jobs n] [--pr-limit n] [--pr-jobs n] [--no-pr-index] [--no-tool-runners] [--no-tool-index] [--no-data-sheet-facts] [--no-rebuild]",
    "  decomp-orchestrator [global flags] kg-rebuild-graph [--graph-db path] [--sources all-or-comma-list] [--agent-state-enrichment jsonl] [--knowledge-curator-enrichment jsonl]",
    "  decomp-orchestrator [global flags] kg-search --query text [--source id] [--limit n] [--graph-db path] [--rebuild]",
    "  decomp-orchestrator [global flags] kg-smoke [--graph-db path] [--rebuild] [--strict]",
    "  decomp-orchestrator [global flags] kg-file-card --source path [--graph-db path] [--rebuild]",
    "  decomp-orchestrator [global flags] kg-rank-features [--limit n] [--candidate-limit n] [--graph-db path] [--rebuild]",
    "  decomp-orchestrator [global flags] status",
    "",
    "Global flags:",
    "  --project <id>             resolve repo/state/graph defaults from projects/<id>/project.json",
    "  --repo-root <path>          default: current working directory",
    `  --state-dir <path>         default: project state dir with --project, otherwise <cwd>/${DEFAULT_STATE_DIR_NAME}`,
    "  --dry-run-agents           do not call Pi SDK; write prompts as outputs",
    `  --provider <name>          default: ${DEFAULT_PI_PROVIDER}`,
    `  --model <name>             default: ${DEFAULT_PI_MODEL}`,
    `  --thinking-level <level>   default: ${DEFAULT_PI_THINKING_LEVEL}`,
    "  --agent-timeout-seconds n  bound each live Pi session; default: no timeout",
    "",
    "Epoch/refill flags:",
    "  --candidate-limit n           initial seed size and compatibility pool size; default: max(32, max workers * 2)",
    "  --queue-target-size n         compatibility default for epoch size and ready queue size; default: max(candidate limit, max workers * 2)",
    "  --epoch-size n|full           total target admissions for one scheduler epoch; default: --queue-target-size",
    "  --epoch-ready-queue-size n    immediately leaseable queued targets kept filled from the admitted epoch set",
    "  --candidate-window n          initial board candidates scanned for refill; expands when exhausted; default: max(candidate limit, queue target * 8)",
    "  --graph-db path               graph DB used for board ranking; default: selected project graph DB, otherwise knowledge/resource_graph/graph.sqlite",
    "  --queue-refresh-interval-ms n compatibility priority refresh interval for --no-epoch-cycle mode; default: 60000",
    "",
    "Epoch cycle flags (run-loop):",
    "  run-loop runs deterministic scheduler epochs by default: fixed admission, ready-queue refill from",
    "  the admitted set, fast run-evidence refresh during the epoch, and full report truth rebuild at boundary.",
    "  --no-epoch-cycle                       restore continuous queue top-up and watermark-driven replan events",
    "  --epoch-worktree path                  persistent checkpoint worktree; default: <state-dir>/epoch_worktree",
    "  --epoch-configure-command cmd          shell command run in the worktree before each report build; default: python3 configure.py --require-protos",
    "  --epoch-link-paths a,b                 untracked build inputs symlinked from the live repo into the worktree; default: orig",
    "  --epoch-regression-pause-threshold n   pause (no refill) when more than n report rows regress in one epoch; default: 12",
    "  --epoch-regression-requeue-limit n     max regressed functions requeued as priority repairs per epoch; default: 32",
    "  --epoch-retry-ms n                     backoff after an epoch failure, pause, or exhausted board; default: 600000",
    "  --fast-kg-maintenance-interval-ms n    in-epoch kg-maintain --no-tool-runners interval; live default: 180000, dry-run default: 0",
    "  --fast-kg-maintenance-report-count n   coalesced worker-report trigger for fast refresh; default: 16",
    "  --no-fast-kg-maintenance               disable in-epoch fast run-evidence refresh",
    "  --full-kg-maintenance-mode mode        boundary kg-maintain mode: full, no-tool-runners, or skip; default: full",
    "",
    "Run-loop replan flags:",
    "  --queue-low-watermark n        emit deterministic queue-pressure work when total queued work is at/below n while workers are active; default: 25% of queue target size",
    "  --schedulable-low-watermark n  emit deterministic queue-pressure work when unlocked distinct-file work is at/below n while underfilled; default: max workers",
    "  --active-low-watermark n       long-tail active worker threshold; default: 75% of max workers",
    "  --long-tail-replan-ms n        refresh deterministic queue pressure after underfilled long tail persists; default: 300000",
    "  --replan-interval-ms n         periodic deterministic queue-pressure refresh while workers are active; default: 0 disabled",
    "  --replan-cooldown-ms n         minimum delay between run-loop-produced replan events; default: 300000",
    "  --no-blocked-queue-replan      do not emit queue-pressure work when queued work is blocked by active file locks",
    "",
    "Worker validation flags:",
    `  --ttl-seconds n                 worker lease/runtime seconds; default: ${DEFAULT_WORKER_TTL_SECONDS}`,
    "  --repair-attempts n             worker repair turns after failed post-return gate; default: 2 live, 0 dry-run",
    "  progress/score_candidate returns automatically run same-unit runner validation before trust/checkpoint promotion",
    "  --post-return-check-command c   optional shell command run after accepted progress/score_candidate; placeholders: {repo_root} {state_dir} {worker_log_dir} {lease_id} {source_path} {unit} {symbol} {write_set}",
    "",
    "Regression promotion flags:",
    "  report-run --reset-baseline      force-generate report.json, copy it to baseline.json, then generate a zero-delta report_changes.json",
    "  report-run                       force-generate report.json and report_changes.json against the saved baseline",
    "  --require-pr-promotion                   fail clean local-only runs that do not meet the PR promotion policy",
    "  --promotion-min-new-matches n            exact new matches required for PR-ready evidence; default: 1",
    "  --promotion-min-matched-code-bytes n     matched code byte delta required for PR-ready evidence; default: 1",
    "  --promotion-min-matched-data-bytes n     matched data byte delta required for PR-ready evidence; default: 1",
    "  --promotion-min-unmatched-improvement-bytes n  explicit fuzzy-only byte threshold; default: 0 disabled",
    "",
    "QA repair flags:",
    "  qa-repair writes queue.json, summary.json, report.md, and ship_status.json under state_dir/qa_repairs/<run-id>/<timestamp>/",
    "  --scan-json path                 replay a saved review_lint scan_diff JSON instead of running the scanner",
    "  --checkpoint path|none           candidate source from checkpoint.json; omitted means latest run checkpoint when available",
    "  --candidate-files a,b            extra comma-separated source paths to treat as candidates",
    "  --candidate-list path            newline/JSON candidate file list",
    "  --all-scan-files                 when no candidates are supplied, queue every file with scan findings",
    "  --match-only                     exclude improvement_candidate checkpoint items from the sweep",
    "  --run-agents                     run qa-repair over queued items; combine with global --dry-run-agents to write prompts only",
    "  --repair-warnings                queue warning-only findings as repair targets instead of advisory report context",
    "  --max-items n / --item-id id      bound or select repair items for this invocation",
    "  --score-check-command cmd         shell command run after live repair; nonzero blocks clean status; JSON stdout may include preTargetScore/postTargetScore or score_impact",
    "  --build-check-command cmd         shell command run after live repair; nonzero blocks clean status",
    "  --regression-check-command cmd    shell command run after live repair; nonzero blocks clean status",
    "  validation command placeholders: {repo_root} {state_dir} {output_dir} {run_id} {item_id} {source_path} {base_ref}",
    "",
    "Checkpoint flags:",
    "  checkpoint-run                    harvest worker reports into match PR candidates, promoted improvement candidates, and carry-forward items",
    "  --artifact-dir path               write checkpoint.json, pr_candidates.md, and carry_forward.md here; default: state run checkpoint dir",
    "  --allow-active-leases             checkpoint even if active leases remain; normally drain or recover first",
    "  --title text                      markdown title prefix; default: Run checkpoint",
    "  --rework-symbols a,b              symbols that broke or regressed against the rebuilt baseline; their items become needs_rework instead of shipping",
    "  improvement promotion floors come from project pr config (improvementMinGainPoints, improvementMinMatchedBytes); validated non-match gains below the floors stay local as deferred patches",
    "",
    "PR split planning flags:",
    "  --base-ref ref                  branch-diff base for handoff planning; default: origin/master",
    "  --strategy deterministic|agent  deterministic grouping or PR splitter agent proposal; default: project pr.splitStrategy or deterministic",
    "  --group-mode mode               grouping strategy: melee-subsystem or top-dir; default: melee-subsystem",
    "  --max-files-per-pr n            hard ceiling: warn and refine directory groups above this size; default: 30",
    "  --min-files-per-pr n            match slices below this size merge into combined PRs (1 disables); default: 4",
    "  --checkpoint path               checkpoint.json used to split slices into match and improvement PR lanes",
    "  --ship-status path              ship_status.json from ship-set verification; match slices keep only surviving files, dropped files ride the local lane",
    "  --branch-prefix name            branch prefix for suggested slice branches; default: pr-split",
    "  --title-prefix text             PR title prefix for suggested slices; default: Melee decomp",
    "  --agent-output-dir path         where pr-splitter prompt/output artifacts go when --strategy agent is used",
    "  --run-id id                     attach pr-splitter Pi session records to this run when --strategy agent is used",
    "  --slice-check-command cmd       command run inside an isolated slice worktree; default: python configure.py --require-protos && ninja changes_all",
    "  --committed-only                ignore dirty worktree status",
    "  --worktree-only                 ignore committed branch diff",
    "  --no-untracked                  omit untracked files from worktree planning",
    "  --json                          print the split plan as JSON",
    "  --output path                   also write the rendered plan to a file under repo root",
    "",
    "Pre-ship review flags (pr-preship-review):",
    "  --plan path                     required: saved pr-split-plan --json output for the handoff branch",
    "  --all                           review every shipping slice in the plan (local-only lanes are skipped)",
    "  --slice id                      review one slice by plan id (works for local-only slices too)",
    "  --base ref / --head ref         diff range for slice diffs; default: the plan's baseRef/headRef",
    "  --include-worktree              review git diff <base> against the current worktree instead of base/head refs",
    "  --thinking level                agent thinking level for the review; default: global --thinking-level",
    "  --run-id id                     artifact namespace under state_dir/preship_reviews/; default: manual",
    "  --dry-run                       build and write prompts + slice diffs, skip the agent call",
    "  exit 1 when any slice or finding verdict is reject, or on any agent/tool failure (fail-closed)",
    "",
    "Draft PR QA lifecycle flags (pr-draft-qa):",
    "  --pr n / --pr-url url            operate on an existing draft PR; the PR is resolved with gh pr view",
    "  --create-draft --title title     create the draft PR first, then run the lifecycle against it",
    "  --repo owner/name                GitHub repo; defaults from origin remote or doldecomp/melee project",
    "  --base ref / --head ref          local refs used for diff review; defaults to PR base/head OIDs",
    "  --remote name                    remote used to fetch base and pull/<pr>/head; default from project baseRef",
    "  --skip-fetch                     do not fetch PR refs before diffing",
    "  --include-worktree               include uncommitted local edits in preship and scan diffs",
    "  --run-agents                     run qa-repair agents for deterministic findings; implies include-worktree in later rounds",
    "  --max-repair-rounds n            preship/scan/repair loop count; default 2 with --run-agents, otherwise 1",
    "  --comment-unresolved             post deduped GitHub comments for unresolved preship/QA findings",
    "  --comment-warnings               include warning findings in GitHub comments; strict draft QA already treats warnings as unresolved",
    "  --advisory-warnings              allow warning-only findings to be ready-for-review artifacts instead of repair blockers",
    "  --no-repair-warnings             keep warnings strict in final status but do not queue warning-only files for qa-repair",
    "  --allow-lower-score-repairs      let clean_lower_score repairs reach ready-with-warnings instead of blocking as needs_repair",
    "  --skip-comment-intake            skip fetching existing PR/issue comments and review comments",
    "  --wait-ci / --skip-ci            wait for GitHub PR checks, or skip the CI snapshot entirely",
    "  --local-check-command cmd        final shell check; placeholders: {repo_root} {state_dir} {output_dir} {run_id} {pr} {base_ref} {head_ref}",
    "  --score-check-command cmd / --build-check-command cmd / --regression-check-command cmd",
    "                                   validation commands forwarded to qa-repair item processing",
    "  writes summary.json, report.md, comments.json, github_comments.json, per-round plan/diff/scan/repair artifacts under state_dir/pr_draft_qa/pr-<n>/<run-id>/",
    "",
    "Save point flags:",
    "  --trigger kind                   what boundary produced this save point; default: manual (epoch save points are written by the epoch cycle)",
    "  --label text                     human label recorded with the save point and used in the commit message",
    "  --no-commit                      capture the save point without committing the dirty worktree",
    "  --list / --limit n               print recent save points instead of creating one",
    "  save-point commits never stage decomp-orchestrator/ or the state dir; report.json/report_changes.json are copied under state_dir/save_points/<timestamp>/",
    "",
    "Reconcile flags:",
    "  --mode ship-validate|sync-merge  ship-validate fixes regressions before PR handoff; sync-merge resolves conflicts/dupes/build errors after upstream sync; default: ship-validate",
    "  --attempt-budget n               fix/rebuild/re-report cycles before the agent escalates; default: 3",
    "  --context-file path              extra operator-provided JSON context merged into the agent prompt",
    "  --allow-missing-regression-check run ship-validate without a prior regression-check summary",
    "",
    "Knowledge maintenance flags:",
    "  --knowledge-maintenance-interval-ms n  background kg-maintain interval in run-loop; live default: 300000, dry-run default: 0",
    "  --no-knowledge-maintenance             disable run-loop background knowledge maintenance",
    "  --run-pr-agent                         let kg-maintain call the PR review agent for pending PR postmortems; run-loop live maintenance enables this by default",
    "  --no-run-pr-agent                      keep run-loop background PR indexing deterministic",
    "  --run-curator-agent                    let kg-maintain call the knowledge-curator agent for proposal review",
    "  --curator-agent-record-limit n         sampled deterministic records sent to the curator agent; default: 40",
    "  --curator-agent-batch-size n           deterministic records per curator-agent batch; default: record limit",
    "  --curator-agent-jobs n                 concurrent curator-agent batches; default: 16",
    "  --pr-limit n                           max pending PRs or PR lessons considered by maintenance; 0 means no PR indexing limit",
    "  --pr-jobs n                            concurrent PR postmortem workers; default: 16",
    "  --no-tool-runners                      skip live knowledge tool runner refresh during kg-maintain",
    "  --no-tool-index                        skip generated knowledge tool indexes during kg-maintain",
    "  --no-data-sheet-facts                  skip codebase-derived SSBM data-sheet fact generation during kg-maintain",
    "  --no-rebuild                           skip graph rebuild after knowledge maintenance refreshes",
    "",
    "Babysit flags:",
    "  --system-command <name>    child system command: run-loop, bootstrap, or trigger-agent; default: run-loop",
    "  --max-restarts n           incident restarts; 0 means unlimited",
    "  --max-system-runs n        stop after n child runs; 0 means unlimited",
    "  --restart-delay-ms n       delay before a restart; default: 1000",
    "  --restart-on-clean-exit    restart even after a clean child exit",
    "  --force-recover-leases     force all active leases on non-worker incidents",
    "  --no-recover-leases        skip guardian lease recovery",
    "  --worker-thinking-level l  pass a different thinking level to worker subprocesses",
  ].join("\n");
}
